# Generated by Django 4.1.1 on 2022-09-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_pets_allowed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='addreess',
            new_name='address',
        ),
    ]
